[collections.group1ck]

[collections.group2ck]

[collections.group3ck]

[groups.default.rules.read]
template = "collection(any()).anyRead()"

[groups.default.rules.write]
template = "collection(any()).anyWrite()"
